#!/usr/bin/env bash

function rmdir {
    rm -rf ./$1;
    mkdir ./$1;
    cd ./$1;
    touch .gitkeep;
    cd ./../;
};

# removing build outputs
rmdir cmake-build-debug;

# removing project dependencies
rmdir libs;


# removing built web dependencies
rmdir www/libs;
