#!/usr/bin/env bash

source utils;


goToLibs;#============================================================================================================#
#  DEPS                                                                                                         ~
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#/
# * DEBIAN :
sudo apt install    inotify-tools;
sudo apt install    cmake;
sudo apt install    openssl;
sudo apt install    libssl-dev;

# * C(++) :
##--| lib name |---| branch |------| git repo |------------------------------------------| (c)make command(s) |------#\

# rang (Terminal colour utility)                                                                                      #
install rang        master          https://github.com/agauniyal/rang.git;

# Catch2 (Unit testing framework)                                                                                     #
install catch2      master          https://github.com/catchorg/Catch2.git;

# DotEnv (.env file parser)                                                                                           #
install cpp-dotenv  master          https://github.com/adeharo9/cpp-dotenv.git;

# Json (A .json parser)                                                                                               #
install json        master          https://github.com/kazuho/picojson.git;

# Serializer (Save / Load objects)                                                                                    #
install serializer  master          https://github.com/eyalz800/serializer.git;

checkForRemovedDependencies; #  ~   ~   ~   ~   ~   ~   ~   ~   ~   ~   ~   ~   ~   ~   ~   ~   ~   ~   ~   ~   ~   ~