#!/usr/bin/env bash

source async;
source utils;

# Configuration
ico=$(pwd)/images/cpp.png;   # Icon of the image used for notifications
dirs="./src/";               # Folders to watch

# Function called at each folder source code update
function buildAndRun() {
    removePreviousNotifications;
    notify-send -i "${ico}" "Source code updated!" "File update detected in one of these folders ${dirs}, now re-compiling ...";
    make;
    removePreviousNotifications;
    notify-send -i "${ico}" "Compilation done!" "Now running the software ...";
    run;
};

# Start watcher
watch "${dirs}" buildAndRun;

